/* ---------------------------------------------------------------------------
   Provider selection — the seam for future custom ML.

   Today exactly one implementation is registered: the local, deterministic
   intelligence engine. It consults no external service.

   To connect a Python inference API in a later phase, implement AIProvider
   against it and return it from getProvider(). No component changes, because
   nothing outside this module imports a concrete engine.
--------------------------------------------------------------------------- */
import type { AIProvider } from "./types";
import type { ChatProvider } from "./chat";
import { LocalIntelligenceEngine } from "./intelligenceEngine";
import { LocalChatEngine } from "./chatEngine";
import { RealLLMProvider } from "./realLlmProvider";
import { probeBackend, cachedBackendStatus } from "./backendClient";

/**
 * Lazily constructed.
 *
 * chatEngine imports getProvider() from this module while this module imports
 * LocalChatEngine from chatEngine — a legitimate cycle, since each only calls
 * the other at runtime. Constructing at module scope resolved that cycle
 * during initialisation and threw "LocalChatEngine is not a constructor".
 * Deferring construction to first call breaks the init-time dependency while
 * keeping the provider seam intact.
 */
let localEngine: AIProvider | null = null;
let localChat: ChatProvider | null = null;

export function getProvider(): AIProvider {
  // Future: if an inference endpoint is configured, return that provider here.
  if (!localEngine) localEngine = new LocalIntelligenceEngine();
  return localEngine;
}

/**
 * Conversational provider. Swap this for an LLM- or RAG-backed implementation
 * of ChatProvider in a later phase — no component imports a concrete engine.
 */
export function getChatProvider(): ChatProvider {
  if (!localChat) localChat = new LocalChatEngine();
  return localChat;
}

let realChat: ChatProvider | null = null;

/**
 * Routing provider.
 *
 * Tries the real model when the proxy reports one configured, and falls back to
 * the deterministic engine on ANY failure — unconfigured, unreachable, timed
 * out, rate limited or unparseable. The assistant therefore never becomes
 * unavailable because a model is down.
 */
class RoutingChatProvider implements ChatProvider {
  readonly id = "rule_based" as const;
  readonly label = "Routing";

  async respond(question: Parameters<ChatProvider["respond"]>[0], intent: Parameters<ChatProvider["respond"]>[1], context: Parameters<ChatProvider["respond"]>[2]) {
    await probeBackend();

    if (RealLLMProvider.isConfigured()) {
      if (!realChat) realChat = new RealLLMProvider();
      try {
        return await realChat.respond(question, intent, context);
      } catch (err) {
        // Logged, then degraded. The analyst gets an answer either way.
        console.warn(
          "[socgenie/ai] real provider failed, using deterministic fallback:",
          err instanceof Error ? err.message : "unknown"
        );
      }
    }

    if (!localChat) localChat = new LocalChatEngine();
    return localChat.respond(question, intent, context);
  }
}

let routing: ChatProvider | null = null;

/** What the UI should call. Handles provider selection and fallback. */
export function getRoutingChatProvider(): ChatProvider {
  if (!routing) routing = new RoutingChatProvider();
  return routing;
}

/**
 * Three explicit states. There is no path that reports CONNECTED without a
 * verified backend proxy, so the UI cannot accidentally imply one.
 */
export type ProviderState = "LOCAL_FALLBACK" | "REAL_MODEL_NOT_CONFIGURED" | "REAL_MODEL_CONNECTED";

export interface ProviderStatus {
  state: ProviderState;
  label: string;
  detail: string;
  connected: boolean;
}

export function providerStatus(): ProviderStatus {
  const backend = cachedBackendStatus();

  if (backend && backend.reachable && !backend.configured) {
    return {
      state: "REAL_MODEL_NOT_CONFIGURED",
      label: "Rule-based analysis",
      detail:
        "The backend proxy is running but no model provider is configured. Responses come from the local deterministic engine with retrieval from the curated knowledge base.",
      connected: false,
    };
  }

  if (RealLLMProvider.isConfigured()) {
    return {
      state: "REAL_MODEL_CONNECTED",
      label: "AI analysis",
      detail: `Responses are generated by ${backend?.model ?? "a configured model"} through the backend proxy. Retrieval and output validation still apply.`,
      connected: true,
    };
  }
  return {
    state: "LOCAL_FALLBACK",
    label: "Rule-based analysis",
    detail:
      "No external model is configured. Responses come from the local deterministic engine with retrieval from the curated knowledge base. Nothing is sent off this machine.",
    connected: false,
  };
}

/** Exposed for the admin configuration panel. */
export function realProviderStatus(): { available: boolean; message: string } {
  const backend = cachedBackendStatus();
  if (RealLLMProvider.isConfigured()) {
    return { available: true, message: `Configured via the backend proxy (${backend?.model ?? "model"}). The API key is held server-side and is never sent to the browser.` };
  }
  if (backend?.reachable) {
    return { available: false, message: "Backend proxy is running but no provider is configured. Set LLM_PROVIDER and ANTHROPIC_API_KEY in the server .env." };
  }
  return { available: false, message: "REAL MODEL PROVIDER NOT CONFIGURED — the backend proxy is not reachable. No endpoint, no key, no request is made." };
}
